standardboard = ["Silver Lake Race", "Silver Lake Compact GP", "Silver Lake Eliminator", "Silver Lake Special Event", "Waterfront Burning Lap", "Waterfront Face Off", "Waterfront Muscle GP", "Waterfront Preview Lap", "Lakeside Getaway Face Off 1", "Lakeside Getaway Race", "Lakeside Getaway Face Off 2", "Lakeside Getaway Special Event", "Mountian Parkway Face off 1", "Mountian Parkway Road Rage", "Mountian Parkway Face off 2", "Mountian Parkway Special Event", "Kings of the Road Face Off", "Kings of the Road Race", "Kings of the Road Gold Medal GP", "Downtown Preview lap 1", "Downtown Road Rage 1", "Downtown Race 1", "Downtown Race 2", "Downtown Road Rage 2", "Downtown Preview lap", "Winter City Race", "Winter City Special Event", "Winter City Eliminator", "Frozen Peak Face Off 1", "Frozen Peak Face Off 2", "Alpine Special Event", "Alpine Road Rage", "Alpine Race", "Alpine Face off", "Continental Run Face off 1", "Continental Run Race 1", "Continental Run Race 2", "Continental Run Special Event", "Continental Run Face off 2", "Alpine Expressway Race", "Alpine Expressway Sports GP", "Riviera Road Rage 1", "Riviera Burning Lap", "Riviera Eliminator", "Riviera Road Rage 2", "Coastal Dream Preview Lap", "Coastal Dream Race", "Coastal Dream Road Rage 1", "Coastal Dream Road Rage 2", "Vineyard Special Event", "Vineyard Road Rage 1", "Vineyard Face Off", "Vineyard Coupe GP", "Vineyard Road Rage 2", "Vineyard Eliminator", "Island Padadise Special Event", "Island Paradise Race", "Island Paradise Face Off", "Island Paradise Eliminator", "Tropical Drive Preview Lap", "Tropical Drive Race 1", "Tropical Drive Race 2", "Tropical Drive Road Rage", "Tropical Drive Super Grand Prix", "Golden City Special Event", "Golden City Road Rage", "Golden City Race", "Golden City Face off", "Dockside Special Event", "Dockside Eliminator", "Dockside Road Rage 1", "Dockside Face off", "Dockside Road Rage 2", "Gone Fishin'", "Home Wrecker", "Pillar Driller", "Hit The Split", "Tram Ram", "Truck Torpedo", "Euro Tram Ram", "Snowed Under", "Avalanche!", "Paid the Price!", "Riviera Roustabout", "Berth Trauma", "Gate Crasher", "Grapes of Wrath", "Market-Stalled", "Tuk-Down", "Tunnel of Shove", "Ship Wreck", "Rumble in the Jungle", "Catch the Tour Bus", "Easy Takedowns Trophy", "Advanced Takedowns Trophy", "Expert Takedowns Trophy", "Champion Takedowns Trophy", "Custom Compact", "Assassin Compact", "Custom Muscle", "Assassin Muscle", "Custom Coupe", "Assassin Coupe", "Custom Sports", "Assassin Sports", "Custom Super", "Assassin Super"];
eventsonlyboard = ["Silver Lake Race", "Silver Lake Compact GP", "Silver Lake Eliminator", "Silver Lake Special Event", "Waterfront Burning Lap", "Waterfront Face Off", "Waterfront Muscle GP", "Waterfront Preview Lap", "Lakeside Getaway Face Off 1", "Lakeside Getaway Race", "Lakeside Getaway Face Off 2", "Lakeside Getaway Special Event", "Mountian Parkway Face off 1", "Mountian Parkway Road Rage", "Mountian Parkway Face off 2", "Mountian Parkway Special Event", "Kings of the Road Face Off", "Kings of the Road Race", "Kings of the Road Gold Medal GP", "Downtown Preview lap 1", "Downtown Road Rage 1", "Downtown Race 1", "Downtown Race 2", "Downtown Road Rage 2", "Downtown Preview lap", "Winter City Race", "Winter City Special Event", "Winter City Eliminator", "Frozen Peak Face Off 1", "Frozen Peak Face Off 2", "Alpine Special Event", "Alpine Road Rage", "Alpine Race", "Alpine Face off", "Continental Run Face off 1", "Continental Run Race 1", "Continental Run Race 2", "Continental Run Special Event", "Continental Run Face off 2", "Alpine Expressway Race", "Alpine Expressway Sports GP", "Riviera Road Rage 1", "Riviera Burning Lap", "Riviera Eliminator", "Riviera Road Rage 2", "Coastal Dream Preview Lap", "Coastal Dream Race", "Coastal Dream Road Rage 1", "Coastal Dream Road Rage 2", "Vineyard Special Event", "Vineyard Road Rage 1", "Vineyard Face Off", "Vineyard Coupe GP", "Vineyard Road Rage 2", "Vineyard Eliminator", "Island Padadise Special Event", "Island Paradise Race", "Island Paradise Face Off", "Island Paradise Eliminator", "Tropical Drive Preview Lap", "Tropical Drive Race 1", "Tropical Drive Race 2", "Tropical Drive Road Rage", "Tropical Drive Super Grand Prix", "Golden City Special Event", "Golden City Road Rage", "Golden City Race", "Golden City Face off", "Dockside Special Event", "Dockside Eliminator", "Dockside Road Rage 1", "Dockside Face off", "Dockside Road Rage 2"];

function generate(a) {
    for (let i = a.length - 1; i > 0; i--) {
        const j = Math.floor(Math.random() * (i + 1));
        [a[i], a[j]] = [a[j], a[i]];
    }
	
	var card = []
	for (let i = 0;  i < 25; i++) {
		card[i] = {name: a[i]};
	}
    clipboardTmp = document.createElement("textarea");	
	clipboardTmp.value = JSON.stringify(card);
	document.body.appendChild(clipboardTmp)
	clipboardTmp.focus();
	clipboardTmp.select();
	document.execCommand('copy');
	document.body.removeChild(clipboardTmp)
}
